### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by blake-hamm** [blake-hamm/bhamm-lab#1]
Some items to get the full fruition from this monorepo:

- [x] Install gitea as primary scm with issues/project management - https://docs.gitea.com/installation/install-on-kubernetes
    - [x] Authelia and traefik config
- [ ] Push mirror with github - https://docs.gitea.com/usage/repo-mirror
- [ ] Setup docs site + update deploy docs
- [ ] Test out some gitea actions

Now, the primary monorepo should be setup and we have a project management process to follow. Next steps:

- [ ] Setup libvirtd terraform
- [ ] Install opnsense (with backup)
- [ ] Setup opnsense (with ansible)

**Comment by blake-hamm** [comment]
Copied into gitea
